apiVersion: v1
kind: Pod
metadata:
  name: node-js-pod
spec:
  containers:
  - name: node-js-pod
    image: jonbaier/node-express-info:latest
    ports:
    - containerPort: 80
    livenessProbe:
      # An HTTP health check 
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 1
    readinessProbe:
      # An HTTP health check 
      httpGet:
        path: /status/
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 1