apiVersion: v1
kind: Pod
metadata:
    name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: jonbaier/node-express-info:latest
    ports:
    - containerPort: 80
      name: web
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-phrases
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-phrases